### ISSUE TITLE
Find a free room for a specific timeslot

### ISSUE THREAD

**Issue by SamMonier** [cristinameda/GL02_TIJA#3]
TypeError: analyzer.searchAvailableRooms is not a function, for the functionnality: find a free room for a specific timeslot.
More details for the specification: the student is expected to enter a timeslot and the file containing the data, the software is expected to return all free rooms available during that time in an easily readable format.

**Comment by cristinameda** [comment]
The same error when calling: 
node RoomManagementCLI.js searchAV ./data/AB/edt.cru -d Friday -s 09:00 -e 12:00
I don't know exactly what the day and time format is, cause it's not mentioned anywhere and I can't find the code for it

**Comment by HommePretentieux** [comment]
the function didn't exist, i made it and it should work
here's an example of the command :
$ node RoomManagementCLI.js searchAV ./data/AB/edt.cru -d "J" -s "08:00" -e "10:00"
info: The available rooms on J 08:00 10:00 are: B103, P101
