### ISSUE TITLE
searchFreeSlot inexistent room considered as existent room with all timeslots free

### ISSUE THREAD

**Issue by cristinameda** [cristinameda/GL02_TIJA#9]
node RoomManagementCLI.js searchFreeSlot ./data/AB/edt.cru S105

will diplay:

info: The room S105 is free on these time slots: 
    L 08:00-20:00
    MA 08:00-20:00
    ME 08:00-20:00
    J 08:00-8:00
    J 12:00-20:00
    V 08:00-20:00
    S 08:00-20:00
    D 08:00-20:00

even though the S105 is not found in the ./data/AB/edt.cru file.

They considered that if it's not found in the file then it's a room that has not been occupied but i don't think the functionality should be that way. Cause in this case, every input is a valid room (i tried with "apple" and it is considered as a room too with all timeslots available), so if a user will write a wrong room code by mistake, he will think it's available all time.

I think it needs to be changed so that if the room code is not in the file, the system displays an error message (inexistent room).

**Comment by shinlns** [comment]
The problem is solved.
If the user try to input a inexistent room it's going to generate an error saying that the room is inexistent.
